import "src/app/globals.css";
import { ToastProvider } from "./providers/ToastProvider";
import TanstackProvider from "./providers/TanstackProvider";
import { Metadata } from "next";
import Provider from "./providers/Provider";
import { getServerSession } from "next-auth";
export const metadata: Metadata = {
  title: "Your Ways Delivery",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          <ToastProvider>
            <TanstackProvider>{children}</TanstackProvider>
          </ToastProvider>
        </Provider>
      </body>
    </html>
  );
}
